site_name: WLAN Pi Documentation Project
nav:
    - Home: index.md
    - V2 Image Docs: v2/index.md
    - V1 Image Docs: v1/index.md
    - Suppliers: suppliers.md
    - News: news.md
    - Support: support.md
    - Getting Involved: v2/get_involved.md
    - V2: 
        - Home: v2/index.md
        - About: v2/about.md
        - Getting Started:
            - Overview: v2/getting_started_overview.md
            - Buy a Kit: v2/getting_started_buy_kit.md
            - Build Your Own: v2/getting_started_build_your_own.md
        - Packages: 
            - Overview: v2/packages.md
            - Perf Measurement:
                - HTML Speedtest: v2/pkg_perf_speedtest.md
                - iPerf: v2/pkg_perf_iperf.md
            - Analysis:
                - Scapy: v2/pkg_analysis_scapy.md
                - extcap: v2/pkg_analysis_extcap.md
            - Utilities:
                - Wi-Fi Console: v2/pkg_util_wconsole.md
                - Hotspot Mode: v2/pkg_util_hotspot.md
                - Wiperf: v2/pkg_util_wiperf.md
                - Profiler: v2/pkg_util_profiler.md
        - Videos: v2/videos.md
        - Suppliers: v2/suppliers.md
        - FAQ: v2/faq.md
        - Getting Involved:
            - Overview: v2/get_involved.md
            - Coding for the WLAN Pi: v2/get_involved_coding.md
            - Non-coder Contribution Opportunties: v2/get_involved_non_coding.md
            - Bug Reports: v2/get_involved_bugs.md
            - Feature Suggestions: v2/get_involved_requests.md
        - Useful Links: v2/useful_links.md
    - V1:
        - Home: v1/index.md
        - About: v1/about.md
        - Getting Started:
            - Overview: v1/getting_started_overview.md
            - Buy a Kit: v1/getting_started_buy_kit.md
            - Build Your Own: v1/getting_started_build_your_own.md
        - Packages: 
            - Overview: v1/packages.md
            - Perf Measurement:
                - HTML Speedtest: v1/pkg_perf_speedtest.md
                - iPerf: v1/pkg_perf_iperf.md
                - Ruckus Zap: v1/pkg_perf_zap.md
            - Analysis:
                - Kismet: v1/pkg_analysis_kismet.md
                - Horst: v1/pkg_analysis_horst.md
                - Scapy: v1/pkg_analysis_scapy.md
                - Termshark: v1/pkg_analysis_termshark.md
                - extcap: v1/pkg_analysis_extcap.md
            - Utilities:
                - Wi-Fi Console: v1/pkg_util_wconsole.md
                - Hotspot Mode: v1/pkg_util_hotspot.md
                - Wiperf: v1/pkg_util_wiperf.md
                - Profiler: v1/pkg_util_profiler.md
        - Videos: v1/videos.md
        - Suppliers: v1/suppliers.md
        - FAQ: v1/faq.md
        - Useful Links: v1/useful_links.md
theme:
    name: 'material'
    icon:
        logo: material/wifi
    language: en
    features:
        - tabs
extra_css:
  - extra.css
markdown_extensions:
  - admonition
plugins:
    - search
    - git-revision-date-localized
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/wlan-pi
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/wlanpi